# Generated by Django 5.2.8 on 2025-12-23 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallereserva',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiesta.promocion'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiesta.promocion'),
        ),
        migrations.AlterField(
            model_name='detallereserva',
            name='tipo',
            field=models.CharField(choices=[('C', 'Combo'), ('S', 'Servicio'), ('P', 'Promoción')], max_length=1),
        ),
    ]
