# Generated by Django 5.2.8 on 2025-12-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0002_detallereserva_promocion_itemcarrito_promocion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='transferencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='PAGO_PENDIENTE', max_length=50),
        ),
    ]
