# Generated by Django 5.2.8 on 2025-12-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0002_itemcarrito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'verbose_name': 'Item Carrito', 'verbose_name_plural': 'Items Carrito'},
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='itemcarrito',
            table='item_carrito',
        ),
    ]
