# Generated by Django 5.2.8 on 2025-12-16 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0002_alter_reserva_options_carrito_itemcarrito'),
        ('fiesta', '0003_alter_itemcarrito_options_alter_itemcarrito_cantidad_and_more'),
    ]

    operations = [
    ]
