# Generated by Django 5.2.8 on 2025-12-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0003_reserva_comprobante_pago_reserva_metodo_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=20)),
                ('tipo_cuenta', models.CharField(max_length=50)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('beneficiario', models.CharField(default='Burbujitas de Colores', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Pago',
                'verbose_name_plural': 'Configuraciones de Pago',
                'db_table': 'configuracion_pago',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='transaccion_id',
            field=models.CharField(blank=True, help_text='ID devuelto por la pasarela (Payphone, Stripe, etc)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], default='transferencia', max_length=20),
        ),
    ]
