# Generated by Django 5.2.8 on 2025-12-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0003_pago_referencia_bancaria_alter_pago_estado_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Día Bloqueado',
                'verbose_name_plural': 'Días Bloqueados',
                'db_table': 'dia_bloqueado',
            },
        ),
        migrations.RemoveField(
            model_name='pago',
            name='referencia_bancaria',
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(default='PENDIENTE', max_length=50),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
