# Generated by Django 5.2.7 on 2025-12-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0003_alter_reserva_options_registrousuario_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrousuario',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
