# Generated by Django 5.2.8 on 2025-12-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0004_configuracionpago_reserva_transaccion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20),
        ),
    ]
