# Generated by Django 5.2.8 on 2025-12-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0004_diabloqueado_remove_pago_referencia_bancaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diabloqueado',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='diabloqueado',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
