# Generated by Django 5.2.8 on 2026-01-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0005_rename_fecha_creacion_diabloqueado_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaBloqueado',
        ),
    ]
