# Generated by Django 5.2.8 on 2026-01-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiesta', '0008_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='promocion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
