"""
Django settings for eventos project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import environ
from pathlib import Path

# 1. DEFINIR BASE_DIR PRIMERO (Fundamental)
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. INICIALIZAR ENVIRON
env = environ.Env()
# Leer el archivo .env ubicado DOS NIVELES arriba de BASE_DIR
env_path = os.path.join(BASE_DIR.parent.parent, '.env')
environ.Env.read_env(env_path)

# 3. AJUSTES DE SEGURIDAD (Usa el .env para la SECRET_KEY)
SECRET_KEY = env('SECRET_KEY', default='django-insecure-t)5l!wsq0oapv4znr%kg!o+v!3-k34t$+(^lws^xyqrl+8(2!*')
DEBUG = env.bool('DEBUG', default=True)

# 4. CONFIGURACIÓN DE BREVO (ANYMAIL)
# Leemos la API Key desde el entorno; si no existe, usa un string vacío
BREVO_API_KEY = env('BREVO_API_KEY', default='')

# Backend de Anymail para Brevo (si no hay API key, usa consola en desarrollo)
if BREVO_API_KEY:
    EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
    ANYMAIL = {
        "BREVO_API_KEY": BREVO_API_KEY,
    }
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# 5. CONFIGURACIÓN DEL REMITENTE
# Leemos desde el .env o usamos valores por defecto
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='Burbujitas de colores <pepet2799@gmail.com>')
SERVER_EMAIL = env('SERVER_EMAIL', default='pepet2799@gmail.com')


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # --- CONFIGURACIÓN CORS (Añadido 1/2) ---
    'corsheaders', 
    # --- FIN CONFIGURACIÓN CORS ---
    'rest_framework',
    'fiesta',
    'rest_framework.authtoken',
    'anymail',  # Para el envío de correos con Brevo
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # --- CONFIGURACIÓN CORS  ---
    'corsheaders.middleware.CorsMiddleware', 
    # --- FIN CONFIGURACIÓN CORS ---
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eventos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'fiesta' / 'templates'],  # Directorio de templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eventos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
    'NAME': 'sandia', 
        'USER': 'postgres', 
        'PASSWORD':'12345',
        'HOST': 'localhost', 
        'PORT': '5432', 
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- AJUSTES ADICIONALES PARA CONEXIÓN DE FRONTEND (CORS) ---
# Esto es necesario para permitir que tu frontend (HTML/JS) se conecte a tu API de Django
CORS_ALLOW_ALL_ORIGINS = True 
# En desarrollo, esto permite peticiones desde cualquier origen (e.g., Live Server)
CORS_ALLOW_ALL_ORIGINS = True

# Nota: configuración de correo ya se maneja arriba mediante environ y BREVO_API_KEY.